---
- hosts: jenkins-slave
  become: true
  environment:
    jenkins_url: "{{ jenkins_url }}"
    jenkins_username: "{{ jenkins_username }}"
    jenkins_password: "{{ jenkins_password }}"
    device_name: "{{ device_name }}"

  tasks:
  - name: update ubuntu repo and cache
    apt:   
      update_cache: yes
      cache_valid_time: 3600

  - name: Install java
    apt: 
      name: openjdk-17-jre
      state: present

  - name: download maven packages
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz 
      dest: /opt

  - name: extract maven packages
    unarchive:
      src:  /opt/apache-maven-3.9.4-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Install git
    apt:
        name: git
        state: present  

  - name: Install wget
    apt:
      name: wget
      state: present              

  - name: Install xmlstarlet
    apt:
      name: xmlstarlet
      state: present    

  - name: Copy Worker PEM File
    copy:
      src: /opt/tp_key  # Replace with the actual path to your local worker.pem file
      dest: /opt/tp_key

  - name: Read SSH private key from file
    command: cat /opt/tp_key
    register: key_file_contents    

  - name: Access group-specific variables
    debug:
      msg: "device_name: {{ device_name }}, jenkins_url: {{ jenkins_url }}, jenkins_username: {{ jenkins_username }}, jenkins_password: {{ jenkins_password }}"

  - name: Set environment variables for jenkins-node.sh script
    set_fact:
      script_environment:
        jenkins_url: "{{ jenkins_url }}"
        jenkins_username: "{{ jenkins_username }}"
        jenkins_password: "{{ jenkins_password }}"
        device_name: "{{ device_name }}"    
        worker_pem: "{{ key_file_contents.stdout }}"
  
  - name: Run Ansible with multiple commands
    ansible.builtin.command: "{{ item }}"
    with_items:
      - apt install unzip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - apt install jq -y

  - name: Execute jenkins-node.sh script
    script: /tmp/jenkins-node.sh
    environment: "{{ script_environment }}"
 

      